export const mockProducts = [
  {
    id: 1,
    product_image: '/assets/products/img-01.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 2,
    product_image: '/assets/products/img-02.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 3,
    product_image: '/assets/products/img-03.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 4,
    product_image: '/assets/products/img-04.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 5,
    product_image: '/assets/products/img-05.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 6,
    product_image: '/assets/products/img-06.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 7,
    product_image: '/assets/products/img-07.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 8,
    product_image: '/assets/products/img-08.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 9,
    product_image: '/assets/products/img-09.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 10,
    product_image: '/assets/products/img-10.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 11,
    product_image: '/assets/products/img-11.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 12,
    product_image: '/assets/products/img-12.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 13,
    product_image: '/assets/products/img-13.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 14,
    product_image: '/assets/products/img-14.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 15,
    product_image: '/assets/products/img-15.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 16,
    product_image: '/assets/products/img-16.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 17,
    product_image: '/assets/products/img-17.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 18,
    product_image: '/assets/products/img-18.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 19,
    product_image: '/assets/products/img-19.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 20,
    product_image: '/assets/products/img-20.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 21,
    product_image: '/assets/products/img-21.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 22,
    product_image: '/assets/products/img-22.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 23,
    product_image: '/assets/products/img-23.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 24,
    product_image: '/assets/products/img-24.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
  {
    id: 25,
    product_image: '/assets/products/img-25.png',
    product_name: '[what happen] How to create ',
    price: 2500,
    like_count: 236,
  },
];
